---

- name: Install prtg-mini-probe
  include_tasks: "install.yml"
  when: prtg_mini_probe_state == "present"

- name: Uninstall prtg-mini-probe
  include_tasks: "uninstall.yml"
  when: prtg_mini_probe_state == "absent"
